title: Jen Trudell
description: Developer

url: http://jtrudell.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown

gems: [jekyll-paginate]

paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Projects
   url: /projects/index.html
 - title: About
   url: /about/index.html
 - title: Contact
   url: /contact/index.html

social:
   github: jtrudell
   twitter: jktrudell
   linkedin: jktrudell
   email: jtrudell@gmail.com

google_analytics: "UA-68107348-1"
