title: Jen Trudell
description: Developer

url: http://jtrudell.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Projects
   url: /projects.html
 - title: About
   url: /about.html
- title: Resume
    url: /resume.html
 - title: Contact
   url: /contact.html

social:
   github: jtrudell
   twitter: jktrudell
   linkedin: jktrudell
   email: jtrudell@gmail.com

google_analytics: "UA-68107348-1"
